version: "2"

volumes:
  nfsportainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.100,rw,nfsvers=4,async
      device: ":/mnt/barracuda/nfsportainer"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 3004:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfsportainer:/data
